#!/bin/sh
#build-cmd
#git checkout -f
#git fetch
git commit -m "up"
git pull origin dev
git push xmrproxy

# git pull origin master
mkdir build
cd build
# (patch include header /usr/include/uuid.h)
cmake ..
#-DCMAKE_EXE_LINKER_FLAGS=-L/usr/local/lib -DCMAKE_SHARED_LINKER_FLAGS=-L/usr/local/lib
make
